server:
  port: 8890
  tomcat:
    threads:
      max: 1000
      min-spare: 30
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://lmxdxl99.com.cn:3306/data_class_4?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 20010720Lmx

